# Generated by Django 5.1.5 on 2025-01-20 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('item', models.CharField(help_text='Name of the item ordered', max_length=100)),
                ('price', models.FloatField(help_text='Price of the ordered item')),
                ('order_number', models.CharField(error_messages={'unique': 'An order with this number already exists'}, help_text='Unique order identifier', max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(help_text='The customer placing the order', on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='customers.customer')),
            ],
        ),
    ]
